### ISSUE TITLE
Killer System

### ISSUE THREAD

**Issue by STGPrince** [syntacs-coetus/stgaming_samp#4]
Due to high technology the city of San Fierro and neighbors have invented Killer detection system
- [x] Killers will now be penalized with killer points. Done in #2 
- [x] High Killer Points means Higher Star Level and Higher Bounty. Done in #2
- [x] Players can avoid getting Killer points by buying anti-killer detection items
- [x] All of this items will be time based: Done in #2
  - 3 minutes
  - 5 minutes
  - 10 minutes
  - 15 minutes
  - 20 minutes
  - 30 minutes
- [x] Dying removes anti-killer detection
- [ ] Cop Players who kills a KP player will gain a little reputation
- [ ] Cop Players who catches a KP player will gain a lot of reputation
